### ISSUE TITLE
OSError in run tmvec-search with "--output-format" set to "alignment"

### ISSUE THREAD

**Issue by CrazyHsu** [tymor22/tm-vec#24]
Hi, thank you for developing such great tool. I tried running the example you gave. `tmvec-build-database` can successfully build the database, and `tmvec-search` has no problem generating tabular results. But when I set the parameter of `tmvec-search` as `--output-format alignment`, I got the following error:
```bash
/home/anaconda3/envs/tmvec/lib/python3.9/site-packages/deepblast/dataset/utils.py:487: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def is_subset(x, y):
/home/anaconda3/envs/tmvec/lib/python3.9/site-packages/deepblast/dataset/utils.py:499: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def __trim_gap(x, k=10):
Sequences inputed
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. If you see this, DO NOT PANIC! This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
ProtTrans model downloaded
Lightning automatically upgraded your loaded checkpoint from v1.5.8 to v2.0.8. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../tm_vec_cath_model.ckpt`
TM-Vec model loaded
meta data loaded
checkpoint1
/mnt/0b4c0b27-228c-4032-80d0-7a7ecca7bfe5/Projects/tmvec/deepblast-l8.ckpt
Traceback (most recent call last):
  File "/home/anaconda3/envs/tmvec/bin/tmvec-search", line 220, in <module>
    align_model = load_model(
  File "/home/anaconda3/envs/tmvec/lib/python3.9/site-packages/deepblast/utils.py", line 52, in load_model
    a = torch.load(model_path)
  File "/home/anaconda3/envs/tmvec/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/anaconda3/envs/tmvec/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/anaconda3/envs/tmvec/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5.py", line 352, in __setstate__
    self.sp_model.Load(self.vocab_file)
  File "/home/anaconda3/envs/tmvec/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/anaconda3/envs/tmvec/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "/mnt/home/jmorton/ceph/prot_t5_xl_uniref50/spiece.model": No such file or directory Error #2

```
Then, I only loaded the `deepblast-l8.ckpt` model of deepblast and I got the following errors:
```bash
In [1]: import torch

In [2]: a = torch.load("/mnt/0b4c0b27-228c-4032-80d0-7a7ecca7bfe5/Projects/tmvec/deepblast-l8.ckpt")
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[2], line 1
----> 1 a = torch.load("/mnt/0b4c0b27-228c-4032-80d0-7a7ecca7bfe5/Projects/tmvec/deepblast-l8.ckpt")

File ~/anaconda3/envs/tmvec/lib/python3.9/site-packages/torch/serialization.py:809, in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    807             except RuntimeError as e:
    808                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 809         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    810 if weights_only:
    811     try:

File ~/anaconda3/envs/tmvec/lib/python3.9/site-packages/torch/serialization.py:1172, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1170 unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1171 unpickler.persistent_load = persistent_load
-> 1172 result = unpickler.load()
   1174 torch._utils._validate_loaded_sparse_tensors()
   1176 return result

File ~/anaconda3/envs/tmvec/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5.py:352, in T5Tokenizer.__setstate__(self, d)
    349     self.sp_model_kwargs = {}
    351 self.sp_model = spm.SentencePieceProcessor(**self.sp_model_kwargs)
--> 352 self.sp_model.Load(self.vocab_file)

File ~/anaconda3/envs/tmvec/lib/python3.9/site-packages/sentencepiece/__init__.py:905, in SentencePieceProcessor.Load(self, model_file, model_proto)
    903 if model_proto:
    904   return self.LoadFromSerializedProto(model_proto)
--> 905 return self.LoadFromFile(model_file)

File ~/anaconda3/envs/tmvec/lib/python3.9/site-packages/sentencepiece/__init__.py:310, in SentencePieceProcessor.LoadFromFile(self, arg)
    309 def LoadFromFile(self, arg):
--> 310     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)

OSError: Not found: "/mnt/home/jmorton/ceph/prot_t5_xl_uniref50/spiece.model": No such file or directory Error #2
```
How can I fix the error? Thank you in advance!

**Comment by mortonjt** [comment]
Moving this to deepblast github

https://github.com/flatironinstitute/deepblast/issues/139
